
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:8080"
    environment:
      openweathermap.api.key: ${OPENWEATHER_API_KEY}
      spring.datasource.url: jdbc:postgresql://postgres:5432/weather
      spring.datasource.username: ${POSTGRES_USER}
      spring.datasource.password: ${POSTGRES_PASSWORD}



volumes:
  postgres_data:


